#! /bin/sh

echo "git status"
git status

read -p 'Should I add all(y/n): ' addall

if [ $addall == 'y' ] || [ $addall == 'Y' ]
then
   echo "pushing all changes!"
   git add .
   git commit -m "Bugs Fixed and performance improved"
   git push origin master

   echo "Pushed all changes"
   echo "Current Status"
   git status
else
   echo "Changes not pushed!"
   echo "Exiting!"
fi
