# Generated by Django 3.2.3 on 2021-05-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('WebSite', models.URLField(null=True)),
                ('About', models.TextField(null=True)),
                ('TeamSize', models.IntegerField()),
                ('Categories', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
