# Generated by Django 3.2.3 on 2021-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20210517_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdvertiserName', models.TextField()),
                ('AdvertiserType', models.TextField()),
                ('SenderReference', models.TextField()),
                ('DisplayReference', models.TextField()),
                ('PostDate', models.TextField()),
                ('Classification', models.TextField()),
                ('SubClassification', models.TextField()),
                ('Position', models.TextField()),
                ('Description', models.TextField()),
                ('Country', models.TextField()),
                ('Location', models.TextField()),
                ('Area', models.TextField()),
                ('PostalCode', models.TextField()),
                ('ApplicationUR', models.TextField()),
                ('DescriptionURL', models.TextField()),
                ('Language', models.TextField()),
                ('ContactName', models.TextField()),
                ('EmploymentType', models.TextField()),
                ('StartDate', models.TextField()),
                ('Duration', models.TextField()),
                ('WorkHours', models.TextField()),
                ('SalaryCurrency', models.TextField()),
                ('SalaryMinimum', models.TextField()),
                ('SalaryMaximum', models.TextField()),
                ('SalaryPeriod', models.TextField()),
                ('SalaryAdditional', models.TextField()),
                ('JobSource', models.TextField()),
                ('JobSourceURL', models.TextField()),
                ('VideoLinkURL', models.TextField()),
                ('AdditionalClassification1', models.TextField()),
                ('AdditionalClassification2', models.TextField()),
                ('AdditionalClassification3', models.TextField()),
                ('AdditionalClassification4', models.TextField()),
                ('LogoURL', models.TextField()),
                ('JobType', models.TextField()),
            ],
        ),
    ]
