# Generated by Django 3.2.3 on 2021-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_xmlfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ApplicationUR',
        ),
        migrations.AddField(
            model_name='job',
            name='ApplicationURL',
            field=models.TextField(null=True),
        ),
    ]
