# Generated by Django 3.2.3 on 2021-05-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_auto_20210517_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xmlFile',
        ),
    ]
