# Generated by Django 3.2.3 on 2021-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_auto_20210517_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
