# Generated by Django 3.2.3 on 2021-05-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_auto_20210517_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='LogoURL',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
