# Generated by Django 3.2.3 on 2021-05-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_auto_20210517_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='PostDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
