# Generated by Django 3.2.3 on 2021-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_auto_20210518_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('addDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
