# Generated by Django 3.2.3 on 2021-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='BlogUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
