# Generated by Django 3.2.3 on 2021-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_blog_blogurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
