# Generated by Django 3.2.3 on 2021-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_alter_blog_blogurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Discription',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='KeyWord',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
