# Generated by Django 3.2.3 on 2021-05-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_auto_20210525_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Discription',
            new_name='Description',
        ),
    ]
