# Generated by Django 3.2.3 on 2021-06-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0020_rename_discription_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True, unique=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('SEO_NAME', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
