# Generated by Django 3.2.3 on 2021-06-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0021_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
    ]
