# Generated by Django 3.2.3 on 2021-08-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0022_auto_20210627_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100, unique=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('cities', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, unique=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('close_designations_comma_separted', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
