# Generated by Django 3.2.3 on 2021-08-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0023_countries_designation_trendingsearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['Country']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['designation']},
        ),
        migrations.AlterModelOptions(
            name='trendingsearch',
            options={'ordering': ['search']},
        ),
    ]
