# Generated by Django 3.2.3 on 2021-08-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0024_auto_20210826_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='popular_jobs_in_loc_comma_separeted',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
