# Generated by Django 3.2.3 on 2021-08-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_auto_20210830_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='salary',
        ),
    ]
