# Generated by Django 3.2.3 on 2021-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0027_remove_designation_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-PostDate']},
        ),
        migrations.AddField(
            model_name='job',
            name='Region',
            field=models.IntegerField(default=1),
        ),
    ]
