# Generated by Django 3.2.3 on 2021-11-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0028_auto_20211011_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='cities',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
