# Generated by Django 3.2.3 on 2022-04-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0029_alter_countries_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_seo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countries',
            name='seo_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='seo_keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='seo_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='show_seo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='seo_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='seo_keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='seo_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='show_seo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='seo_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='seo_keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='seo_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='show_seo',
            field=models.BooleanField(default=False),
        ),
    ]
