# Generated by Django 3.2.3 on 2022-04-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0030_auto_20220409_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='seo_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='seo_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='seo_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_seo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='seo_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='seo_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='seo_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='seo_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='seo_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='seo_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trendingsearch',
            name='seo_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trendingsearch',
            name='seo_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trendingsearch',
            name='seo_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
