# Generated by Django 3.2.3 on 2022-04-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0032_auto_20220409_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Show_On_Homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='Show_On_Homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='Show_On_Homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='Show_On_Homepage',
            field=models.BooleanField(default=True),
        ),
    ]
