# Generated by Django 3.2.3 on 2022-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0034_auto_20220802_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
