# Generated by Django 4.1.1 on 2023-01-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0035_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBlogFeaturedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100, null=True)),
                ('search_show', models.CharField(blank=True, max_length=100, null=True)),
                ('search_country', models.CharField(blank=True, max_length=100, null=True)),
                ('search_country_show', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('body_above_add', models.TextField(blank=True, null=True)),
                ('body_below_add', models.TextField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.jobblogcategory')),
                ('jobs_table', models.ManyToManyField(to='Company.jobblogfeaturedjobs')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
