# Generated by Django 4.1.1 on 2023-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0036_jobblogcategory_jobblogfeaturedjobs_jobblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobblog',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='jobblog',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='jobblog',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobblog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobblog',
            name='seo_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobblog',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='JobBlogCategory',
        ),
    ]
