# Generated by Django 4.1.1 on 2023-01-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0037_rename_create_at_jobblog_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobblogfeaturedjobs',
            old_name='search_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='jobblogfeaturedjobs',
            old_name='search_country_show',
            new_name='country_show',
        ),
    ]
